-- VENUE 

SELECT 
    city, COUNT(*)
FROM
    venue_
GROUP BY city;
/* WHAT CITY HAS THE MOST VENUES? NEW YORK CITY THE MOST VENUES */

SELECT 
    venue_name, COUNT(*)
FROM
    venue_
GROUP BY venue_name
ORDER BY COUNT(*) DESC
LIMIT 1;
/* WHAT VENUE HAS THE HIGHEST COUNT? CENTRAL PARK */

SELECT 
    zip, COUNT(*)
FROM
    venue_
GROUP BY zip
ORDER BY COUNT(*) DESC
LIMIT 5;
/* WHICH ZIP CODE HAS THE MOST VENUES? AND WHAT NEIGHBORHOOD IS THIS? 10003 HAS THE MOST VENUES, AND IT IS EAST VILLAGE/DOWNTOWN/MANHATTEN NY*/


SELECT 
    created, members, GROUP_NAME
FROM
    grp
ORDER BY created;
/* WHAT IS THE LONGEST RUNNING GROUP ON LETSMEET? HOW MANY MEMBERS DO THEY HAVE? 
THE NEW YORK CITY POKER GROUP IS LONGES RUNNING GROUP, STARTING IN 2002 ON 10-08 , AND THEY HAVE 1797 MEMBERS*/

SELECT 
    visibility, members, COUNT(DISTINCT GROUP_ID)
FROM
    grp
GROUP BY visibility
ORDER BY visibility;
/* WHAT DOES PUBLIC_LIMITED MEAN? HOW MANY FROUPS ARE PUBLIC_LIMITED? PUBLIC _LIMITED INFORMS US IF THE GROUP IS OPEN TO THE PUBLIC, OR OPEN AND JUST LIMITED TO A CERTIAN AMOUNT OF MEMBERS.  THERE ARE 514 GROUPS THAT ARE PUBLIC_LIMITED*/

SELECT 
    who, COUNT(*)
FROM
    grp
GROUP BY who
ORDER BY COUNT(*) DESC
LIMIT 6;
/*WHO SHOWS UP IN THE WHO COLUMN THE MOST? MEMBERS, AT 1643 */

SELECT 
    group_id, members, group_name, grp.join_mode
FROM
    GRP
        JOIN
    CATEGORY ON CATEGORY.category_id = grp.category_id
ORDER BY members DESC;
/*WHAT GROUP HAS THE MOST MEMBERS? 20 AND 30 SOMETHINGS CHICAGO, WITH 23380 MEMBERS (GROUP-ID: '1492775') */

SELECT 
    city, COUNT(*)
FROM
    grp_member
GROUP BY city
ORDER BY COUNT(*) DESC
LIMIT 3;
/*WHAT CITY HAS THE MOST MEMBERS? NEW YORK CITY, WITH 23190*/

SELECT 
    *
FROM
    GRP_MEMBER
ORDER BY JOINED
LIMIT 1;
/* CHRISTINE FROM NEW YORK WAS THE FIRST MEMBER IN 2003 AND SHE IS STILL ACTIVE (MEMBER_ID: 257351) */

SELECT 
    COUNT(DISTINCT MEMBER_ID)
FROM
    GRP_MEMBER;
/*HOW MANY DISTINCT MEMBERS ARE THERE? THERE ARE 39980 DISTINCT MEMBERS*/

SELECT 
    city, member_count
FROM
    city
GROUP BY member_count
ORDER BY member_count DESC;
/* WHAT IS THE MEMBER COUNT FOR THE TOP 3 CITIES?  'New York', '229371'; 'Chicago', '90918'; 'San Francisco', '60351' */


SELECT 
    *
FROM
    EVENT;
SELECT 
    (AVG(duration) / 60) / 60
FROM
    event;
/* WHAT IS THE AVERAGE EVENT DURATION? THE AVERAGE DURATION FOR AN EVENT IS APROX. 3 HOURS */

SELECT 
    category.category_id,
    shortname,
    group_id,
    members,
    visibility,
    join_mode
FROM
    category
        JOIN
    grp ON category.category_id = grp.category_id
ORDER BY members DESC
LIMIT 1;
/* WHAT IS THE CATEGORY_ID, SHORTNAME, GROUP_ID FOR THE GROUP WITH THE MOST MEMBERS? IS IT OPEN TO THE PUBLIC?   CATEGORY-ID: 31  SHORTNAME: SOCIAL  GROUP_ID:1492775  AND THEY HAVE 23380 MEMBERS, AND THEY ARE OPEN TO THE PUBLIC*/ 
