-- VENUE 

/* WHAT CITY HAS THE MOST VENUES?*/
SELECT 
    city, COUNT(*)
FROM
    venue_
GROUP BY city;

/*NEW YORK CITY THE MOST VENUES */


/* WHAT VENUE HAS THE HIGHEST COUNT?*/
SELECT 
    venue_name, COUNT(*)
FROM
    venue_
GROUP BY venue_name
ORDER BY COUNT(*) DESC
LIMIT 1;
/* CENTRAL PARK */

/* WHICH ZIP CODE HAS THE MOST VENUES? AND WHAT NEIGHBORHOOD IS THIS?*/
SELECT 
    zip, COUNT(*)
FROM
    venue_
GROUP BY zip
ORDER BY COUNT(*) DESC
LIMIT 5;
/*10003 HAS THE MOST VENUES, AND IT IS EAST VILLAGE/DOWNTOWN/MANHATTEN NY*/

/* WHAT IS THE LONGEST RUNNING GROUP ON LETSMEET? HOW MANY MEMBERS DO THEY HAVE?*/
SELECT 
    created, members, GROUP_NAME
FROM
    grp
ORDER BY created;
/*THE NEW YORK CITY POKER GROUP IS LONGES RUNNING GROUP, STARTING IN 2002 ON 10-08 , AND THEY HAVE 1797 MEMBERS*/

/* WHAT DOES PUBLIC_LIMITED MEAN? HOW MANY FROUPS ARE PUBLIC_LIMITED?*/
SELECT 
    visibility, members, COUNT(DISTINCT GROUP_ID)
FROM
    grp
GROUP BY visibility
ORDER BY visibility;
/*PUBLIC _LIMITED INFORMS US IF THE GROUP IS OPEN TO THE PUBLIC, OR OPEN AND JUST LIMITED TO A CERTIAN AMOUNT OF MEMBERS.  THERE ARE 514 GROUPS THAT ARE PUBLIC_LIMITED*/

/*WHO SHOWS UP IN THE WHO COLUMN THE MOST?*/
SELECT 
    who, COUNT(*)
FROM
    grp
GROUP BY who
ORDER BY COUNT(*) DESC
LIMIT 6;
/*MEMBERS, AT 1643 */

/*WHAT GROUP HAS THE MOST MEMBERS?*/
SELECT 
    group_id, members, group_name, grp.join_mode
FROM
    GRP
        JOIN
    CATEGORY ON CATEGORY.category_id = grp.category_id
ORDER BY members DESC;
/*20 AND 30 SOMETHINGS CHICAGO, WITH 23380 MEMBERS (GROUP-ID: '1492775') */

/*WHAT CITY HAS THE MOST MEMBERS?*/
SELECT 
    city, COUNT(*)
FROM
    grp_member
GROUP BY city
ORDER BY COUNT(*) DESC
LIMIT 3;
/*NEW YORK CITY, WITH 23190*/

/* WHO WAS THE FIRST MEMBER?*/
SELECT 
    *
FROM
    GRP_MEMBER
ORDER BY JOINED
LIMIT 1;
/* CHRISTINE FROM NEW YORK WAS THE FIRST MEMBER IN 2003 AND SHE IS STILL ACTIVE (MEMBER_ID: 257351) */

/*HOW MANY DISTINCT MEMBERS ARE THERE?*/
SELECT 
    COUNT(DISTINCT MEMBER_ID)
FROM
    GRP_MEMBER;
/*THERE ARE 39980 DISTINCT MEMBERS*/

/* WHAT IS THE MEMBER COUNT FOR THE TOP 3 CITIES?*/
SELECT 
    city, member_count
FROM
    city
GROUP BY member_count
ORDER BY member_count DESC;
/*'New York', '229371'; 'Chicago', '90918'; 'San Francisco', '60351' */

/* WHAT IS THE AVERAGE EVENT DURATION?*/
SELECT 
    *
FROM
    EVENT;
SELECT 
    (AVG(duration) / 60) / 60
FROM
    event;
/*THE AVERAGE DURATION FOR AN EVENT IS APROX. 3 HOURS */

/* WHAT IS THE CATEGORY_ID, SHORTNAME, GROUP_ID FOR THE GROUP WITH THE MOST MEMBERS? IS IT OPEN TO THE PUBLIC?*/
SELECT 
    category.category_id,
    shortname,
    group_id,
    members,
    visibility,
    join_mode
FROM
    category
        JOIN
    grp ON category.category_id = grp.category_id
ORDER BY members DESC
LIMIT 1;
/*CATEGORY-ID: 31  SHORTNAME: SOCIAL  GROUP_ID:1492775  AND THEY HAVE 23380 MEMBERS, AND THEY ARE OPEN TO THE PUBLIC*/ 
